---
ldap_server:
  host: localhost
  port: 389
  https: false
  domain: dc=example,dc=org
  admin: admin
  password: admin

organizational_units:
  - name: SolutionEngineering
    users:
    - uid: user1
      cn: User One
      mail: user1@example.org
      user_password: secret123!
    - uid: user2
      cn: User Two
      mail: user2@example.org
      user_password: secret123!
    - uid: user3
      cn: User Three
      mail: user3@example.org
      user_password: secret123!

group_of_names:
  - name: admin
    members:
      - uid: user1
        ou: SolutionEngineering
  - name: user
    members:
      - uid: user2
        ou: SolutionEngineering
      - uid: user3
        ou: Solution Engineering
